### ISSUE TITLE
Idée de nom de package

### ISSUE THREAD

**Issue by gabrielcrepeault** [alec42/Distributacalcul_Package#1]
Je brainstorm, mais qu'est-ce que tu pense de `actcomputer `? `act`, `compute`, `r`.

On pourrait partir la discussion ici

Ce nom de package semble encore disponible : [Packages actuellement sur le CRAN](https://cran.r-project.org/web/packages/available_packages_by_name.html)

**Comment by alec42** [comment]
J'adore l'idée!!
Je me demande si on devrait le donner un nom plus reliée à l'actuariat ou les probabilités / statistiques en général. Qu'est-ce t'en pense?
genre
probcomputer
sinon j'aime actcomputer :)

**Comment by gabrielcrepeault** [comment]
Ouais c'est vrai!

Une autre idée, étant donné que ton projet va être chapeauté par Etienne et
Hélène, tu pourrais l'appeler quantact (à voir s'il y a des copyright sur
ce nom là)

**Comment by alec42** [comment]
Excellente idée!! 
Je vais voir avec eux :)
